<!DOCTYPE html>
<html>
<head>
  <title>Happy Father's Day!</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
      padding-top: 100px;
    }

    h1 {
      font-size: 36px;
    }

    input[type="text"] {
      padding: 10px;
      font-size: 18px;
    }

    input[type="submit"] {
      padding: 10px 20px;
      font-size: 18px;
      background-color: #4CAF50;
      color: white;
      border: none;
      cursor: pointer;
    }

    #message {
      font-size: 24px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <h1>Happy Father's Day!</h1>
  <form id="messageForm">
    <input type="text" id="nameInput" placeholder="Enter your name" required>
    <br><br>
    <input type="submit" value="Submit">
  </form>
  <div id="message"></div>

  <script>
    document.getElementById("messageForm").addEventListener("submit", function(event) {
      event.preventDefault();
      var name = document.getElementById("nameInput").value;
      var message = "Dear Dad, Happy Father's Day, " + name + "! Wishing you a fantastic day filled with joy and love.";
      document.getElementById("message").innerText = message;
    });
  </script>
</body>
</html>
